server:
  port: 8080
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
    timeout: 300
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/forum?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    password: password
    username: root
    #druid相关配置
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 10
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量 maxIdle已经不再使用
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测, 检测需要关闭的空闲连接, 也是作为testWhileIdel执行的依据. 单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间, 单位是毫秒
      min-evictable-idle-time-millis: 30000
      # 校验SQL(必须是一个查询语句), Oracle配置 SELECT 1 FROM DUAL, 如果不配validationQuery项, 则下面三项配置无用
      validation-query: select 'x'
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存preparedStatement,mysql5.5+建议开启
      pool-prepared-statements: true
      # 当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置扩展插件, 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      pool:
        # 当数据库抛出不可恢复的异常时,抛弃该连接
        exception-sorter: true
      # 设置访问druid监控页的账号和密码,默认没有
      stat-view-servlet:
        login-username: root
        login-password: 123456
        enabled: true
        url-pattern: /druid/*
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-log-enabled: true
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-log-enabled: false
  thymeleaf:
    cache: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#文件访问路径
#    static-path-pattern: /file/**
#  resources:
#文件映射的本地路径
#    static-locations: file:D:/uploadPath/

#  Gson配置项
#  gson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    disable-html-escaping: on
#    serialize-nulls: on

#mybatis集成
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
#日志配置
logging:
  config: classpath:logback/logback-spring.xml